services:
  db-mvp:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin321
      POSTGRES_DB: hackathon
    ports:
      - 5400:5432
    volumes:
      - pgdata:/var/lib/postgress/database

volumes:
  pgdata:
